<html xmlns="http://www.w3.org/1999/xhtml">  
<head> 
	<meta http-equiv="Content-Type" content="text/html;charset=utf8" />  
	<title>apidb_test</title>
	<style>
		.a_input {
			width:300px;
		}
		.a_textarea {
			width:100%;
			height:100px;
		}	
		.b_textarea {
			width:100%;
			height:400px;
		}
	</style>
	<script src='http://lib.sinaapp.com/js/jquery/1.8/jquery.min.js' charset='utf-8'></script>
	<script type="text/javascript" charset='utf-8'>
		var API_CONFIG = 
		{
			"login":{
				"name":"用户登陆",
				"url":"/user/login/index",
				"method":"post",
				"params":"telephone=18600622921&password=123456"
			},			
			"changepassword":{
				"name":"修改密码",
				"url":"/user/changepassword/index",
				"method":"post",
				"params":"session_id=18600622921&password=123456&old_password=AWSDFAWDE"
			},			
			"resetpassword":{
				"name":"重置密码",
				"url":"/user/resetpassword/index",
				"method":"post",
				"params":"telephone=18600622921&verify_code=1024&password=123456"
			},			
			"verifycode":{
				"name":"验证验证码",
				"url":"/user/verifycode/index",
				"method":"post",
				"params":"telephone=18600622921&verify_code=1024"
			},			
			"getcode":{
				"name":"获取验证码",
				"url":"/user/getcode/index",
				"method":"post",
				"params":"telephone=18600622921&reset=1"
			},			
			"modify":{
				"name":"修改用户信息",
				"url":"/user/modify/index",
				"method":"post",
				"params":"session_id=18600622921&name=88liang&gender=1&city=beijing&area=chaoyangqu"
			},
			
			"details":{
				"name":"查询用户信息",
				"url":"/user/details/index",
				"method":"post",
				"params":"session_id=18600622921&user_id=88liang"
			},
			"logout":{
				"name":"用户注销",
				"url":"/user/logout/index",
				"method":"post",
				"params":"session_id=18600622921"
			},
			"validate":{
				"name":"手机验证码验证",
				"url":"/user/validate/index",
				"method":"post",
				"params":"session_id=18600622921&verify_code=1024"
			},
			"register":{
				"name":"用户注册",
				"url":"/user/register/index",
				"method":"post",
				"params":"telephone=18600622921&password=FAWSDFAWDE&name=88liang"
			},
			"order":{
				"name":"用户下单",
				"url":"/device/order/index",
				"method":"post",
				"params":"session_id=18600622921&did=123&cid=123&fid=123"
			},
			"buyflow":{
				"name":"购买流量",
				"url":"/flow/buyflow/index",
				"method":"post",
				"params":"session_id=18600622921&fid=123&ccid=asfdafdafdsafdas&starttime=20141101&endtime=20141101"
			},
			"getupgrade":{
				"name":"获取升级信息",
				"url":"/upgrade/getupgrade/index",
				"method":"get",
				"params":"tag=bbbb"
			}
			
		}
	</script>
</head>
<body>
	<p>
	<label>接口名称：</label>
	<select name="request">
	</select>&nbsp;&nbsp;
	<label>接口地址：</label>
	<input type="text" class="a_input" name="request_url" value="/" />&nbsp;&nbsp;
	<label>方法类型：</label>
	<select name="request_method">
		<option value="get">get</option>
		<option value="post">post</option>
	</select>&nbsp;&nbsp;
	<input type="submit" id="request_send" value="send"/>
	</p>
	<p>
		<label>参数：</label><textarea class="a_textarea" name="request_params"></textarea>
	</p>
	<p>
		<label>结果：</label><textarea class="b_textarea" name="request_reponse"></textarea>
	</p>
	<script type="text/javascript">
		$(function() {
			for (var k in API_CONFIG) {
				$('select[name="request"]').append('<option value="'+k+'">'+API_CONFIG[k].name+'</option>');
			}
			$('#request_send').click(function() {
				var url = $('input[name="request_url"]').val();
				var method = $('select[name="request_method"]').val();
				var params = $('textarea[name="request_params"]').val();
				var type = $('select[name="request_type"]').val();

				$.ajax({
				   type: method,
				   url: url,
				   data: params,
				   dataType: 'json',
				   contentType: 'application/x-www-form-urlencoded',
				   async: false,
				   success: function(data){
					   var data = JSON.stringify(data);
				       $('textarea[name="request_reponse"]').val(data);
				   }
				});
			});
			$('select[name="request"]').change(function() {
				set($(this).val());
			});
			set('login');
		});

		function set(k)
		{
			$('input[name="request_url"]').val(API_CONFIG[k].url);
			var method = API_CONFIG[k].method;
			$('option[value="'+method+'"]').attr('selected', '1');
			var str = JSON.stringify(API_CONFIG[k].params).replace(/(^")|("$)/g, "");
			$('textarea[name="request_params"]').val(str);
		}
	</script>
</body>
</html>
