<html xmlns="http://www.w3.org/1999/xhtml">  
<head> 
	<meta http-equiv="Content-Type" content="text/html;charset=utf8" />  
	<title>json_test</title>
	<script src='http://lib.sinaapp.com/js/jquery/1.8/jquery.min.js' charset='utf-8'></script>
</head>
<body>
	<button id='bt'>send</button>
	<script type="text/javascript">
		$(function() {
			alert(33);
			$('#bt').click(function() {
				alert(11);
				var url = '/demo/model/test';
				var method = 'post';
				//		var params = '{"id":12}';
				var params = '[{"status":1},{"status":2}]';
				$.ajax({
				   type: method,
				   url: url,
				   data: params,
				   dataType: "json",
				   contentType: "application/json; charset=utf-8",
				   async: false,
				   success: function(data){
					
				   }
				});
			});
		});
	</script>
</body>
</html>
